apiVersion: v1
kind: Service
metadata:
  name: alertmanager2
spec:
  selector:
    app: alertmanager2
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: alertmanager2
---
